/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        "opensans":['Open Sans', 'sans-serif'],
      },
      colors:{
        'light-bg':'#ffffff',
        "light-border":"#e0e0e0",
        "light-sec":"#f1f3f4",
        "light-text":"#202124",
        "light-h":"#5f6368",
        "light-btn":"#feefc3",
        'dark-bg':'#202124',
        "dark-border":"#5f6368",
        "dark-sec":"#525356",
        "dark-text":"#e8eaed",
        'dark-btn':"#41331c",
        "red":"#f28b82",
        "orange":"#fbbc04",
        "yellow":"#fff475",
        "green":"#ccff90",
        "teal":"#a7ffeb",
        "blue":"#cbf0f8",
        "gray":"#e8eaed",
        "brown":"#e6c9a8",
        "pink":"#fdcfe8",
        "purple":"#d7aefb",
        "darkblue":"#aecbfa",
        "dark-red":"#5c2b29",
        "dark-orange":"#614a19",
        "dark-yellow":"#635d19",
        "dark-green":"#345920",
        "dark-teal":"#16504b",
        "dark-blue":"#2d555e",
        "dark-gray":"#3c3f43",
        "dark-brown":"#442f19",
        "dark-pink":"#5b2245",
        "dark-purple":"#42275e",
        "dark-darkblue":"#1e3a5f",
        },
        backgroundImage:{
          "food":"url(/assets/food.svg)",
          "grocery":"url(/assets/grocery.svg)",
          "music":"url(/assets/music.svg)",
          "notes":"url(/assets/notes.svg)",
          "places":"url(/assets/places.svg)",
          "recipe":"url(/assets/recipe.svg)",
          "celebration":"url(/assets/celebration.svg)",
          "video":"url(/assets/video.svg)",
        }
    },
  },
  plugins: [],
}

